config/routes.rb
Rails.application.routes.draw do
  # We will define any route in our app here
  # Rail routes
  # HTTP_Verb '/url_path', to: 'controller#action', as: :prefix (aka nickname)
  root to: 'pages#home'
  get '/about', to: 'pages#about', as: :about
  get '/contact', to: 'pages#contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # make sure the user is logged in
end

app/controllers/pages_controller.rb
require 'open-uri'

class PagesController < ApplicationController
  # '/about'
  def about
    # By default in Rails
    url = 'https://dictionary.lewagon.com/cat'
    # url = 'https://dictionary.lewagon.com/WHATEVER_THE_USER_SENT_FROM_FORM'
    json = URI.open(url).read
    results = JSON.parse(json)
    @found = results['found']

    # render about.html.erb
  end

  # '/contact'
  def contact
    # Tomorrow's lecture
    # @members = Member.all
    # @members = Member.where(name: params[:member])
    # @members = Member.where('name LIKE ?', "#%{params[:member]}%")
    #
    @members = ['doug', 'celso', 'noemi', 'leo', 'james']
    # when we send info from a form, we have access to the info in the params
    if params[:member].present?
      @members = @members.select do |name|
        name.include?(params[:member])
      end
    end
    # render contact.html.erb
  end

  # '/'
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Intro 1808</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless params[:controller] == 'pages' && params[:action] == 'home' %>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <% end %>
    <%= yield %> <!-- All of our view are displayed here -->
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About</h1>
  <!-- lt + tab -->
  <!-- link_to 'text we see', prefix_path, class: '' -->
  <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <h1>Contact</h1>
  <!-- form -> action (path) and method (http verb) -->
  <!-- input -> type (text/number/email/passowrd) and name (send with this name) -->
  <form action="/contact" method="get">
    <label for="name">Name</label>
    <input type="text" name="member" value='<%= params[:member] %>'>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag :letters, "ABCDEF" %>
    <!-- <input type="hidden" name="authenticity_token" value=<%#= form_authenticity_token %>> -->
    <input type="submit" class="btn btn-primary">
  </form>
  <ul>
    <% if @members.any? %>
      <% @members.each do |member| %>
        <li><%= member %></li>
      <% end %>
    <% else %>
      <li>No members matches <code><%= params[:member] %></code></li>
    <% end %>

  </ul>
  <p>
    <!-- Text Link -->
    <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
    <!-- Wrapped Link -->
    <%= link_to root_path, class: 'btn btn-primary' do %>
      <i class="fa-solid fa-house"></i>
    <% end %>
  </p>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Welcome</h1>
  <p>
    <%= link_to 'About', about_path, class: 'btn btn-primary' %>
  </p>
  <p>
    <%= link_to 'Contact', contact_path, class: 'btn btn-primary' %>
  </p>
</div>

<!-- Ruby logic (dont display) -->
<!-- er + tab -->
<%  %>
<!-- Ruby info (want to display) -->
<!-- pe + tab -->
<%=  %>